/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.InsuranceRole;


import Business.Employee.Employee;
import Business.Employee.User.UserInfo;
import Business.Employee.UserInsurance.UserInsuranceInfo;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;

import javax.swing.JOptionPane;
import javax.swing.JPanel;


import java.awt.CardLayout;

/**
 *
 * @author star
 */
public class ViewInsuranceInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReviewInfoJPanel
     */
    JPanel userProcessContainer;
    LabTestWorkRequest request;
    
  
    private Employee e;


    public ViewInsuranceInfoJPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.e = request.getSender().getEmployee();

        nTf.setEnabled(false);
        sTf.setEnabled(false);
        eTf.setEnabled(false);
        
        takerNameTf.setEnabled(false);
        car_numTf.setEnabled(false);
        carInsNumTf.setEnabled(false);
        carAmTf.setEnabled(false);
        carEtTf.setEnabled(false);
        carStTf.setEnabled(false);
        takerAmTf.setEnabled(false);
        takerEtTf.setEnabled(false);
        takerInsNumTf.setEnabled(false);
        takerStTf.setEnabled(false);
        
        for(UserInfo c : request.getSender().getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
        
        nTf.setText(request.getSender().getEmployee().getName());
        sTf.setText(c.getSsn());
        eTf.setText(c.getEmail());
        car_numTf.setText(c.getCar_num());
        takerNameTf.setText(request.getSender().getEmployee().getName());         
        }
        
        
        
        
        for(UserInsuranceInfo c : request.getSender().getEmployee().getUserInsuranceInfoDirectory().getUserInsuranceInfoDirectory()){
            carAmTf.setText(String.valueOf(c.getCarAmount()));
            carEtTf.setText(c.getCarEndTime());
            takerNameTf.setText(c.getTakerName());
            carInsNumTf.setText(c.getCarInsId());
            car_numTf.setText(c.getCarNumber());
            carStTf.setText(c.getCarStartTime());
            takerAmTf.setText(String.valueOf(c.getTakerAmount()));
            takerEtTf.setText(c.getTakerEndTime());
            takerInsNumTf.setText(c.getTakerInsId());
            takerStTf.setText(c.getTakerStartTime());
//            c.setTakerName(takerName);
//            c.setCarInsId(carInsNum);
//            c.setCarNumber(carNum);
//            c.setCarStartTime(carSt);
//            c.setTakerAmount(takerAm);
//            c.setTakerEndTime(takerEt);
//            c.setTakerInsId(takerInsNum);           
//            c.setTakerStartTime(takerSt);    
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updateInsBtn = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        car_numTf = new javax.swing.JTextField();
        takerNameTf = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        nTf = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sTf = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        eTf = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        carInsNumTf = new javax.swing.JTextField();
        takerInsNumTf = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        carStTf = new javax.swing.JTextField();
        takerStTf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        carEtTf = new javax.swing.JTextField();
        takerEtTf = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        carAmTf = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        takerAmTf = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        saveInsBtn = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel12.setText("------Basic Information-----------------------------------------------------------------------------------------------------");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Check User Profile Information And Add Insurance Here!");

        updateInsBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        updateInsBtn.setText("Update Insurance");
        updateInsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsBtnActionPerformed(evt);
            }
        });

        RejectButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        RejectButton.setText("Reject ");
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Car Number:");

        car_numTf.setEnabled(false);

        takerNameTf.setEnabled(false);

        jLabel20.setText("Name:");

        nTf.setEnabled(false);

        jLabel21.setText("ssn:");

        sTf.setEnabled(false);

        jLabel22.setText("email:");

        eTf.setEnabled(false);

        jLabel23.setText("Taker Insurance ID:");

        carInsNumTf.setEnabled(false);

        takerInsNumTf.setEnabled(false);

        jLabel24.setText("Car Isurance ID:");

        jLabel19.setText("Start Time:");

        carStTf.setEnabled(false);

        takerStTf.setEnabled(false);

        jLabel25.setText("Start Time:");

        jLabel26.setText("End Time:");

        carEtTf.setEnabled(false);

        takerEtTf.setEnabled(false);

        jLabel27.setText("End Time:");

        carAmTf.setEnabled(false);

        jLabel28.setText("Amount:");

        jLabel29.setText("Amount:");

        takerAmTf.setEnabled(false);

        jLabel30.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel30.setText("---------------Taker Insurance---------------");

        jLabel31.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel31.setText("---------------Car Insurance---------------");

        saveInsBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        saveInsBtn.setText("Save");
        saveInsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveInsBtnActionPerformed(evt);
            }
        });

        jLabel32.setText("Taker:");

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AccounterRole/7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel21))
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nTf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sTf)
                                        .addComponent(eTf, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(updateInsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(saveInsBtn)
                                    .addGap(1, 1, 1)
                                    .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(takerStTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(takerEtTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(takerAmTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel23)
                                                .addComponent(jLabel32))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(takerNameTf)
                                                .addComponent(takerInsNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(jLabel29)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(carAmTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel27)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(carEtTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel25)
                                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel17))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(carStTf)
                                                            .addComponent(carInsNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(car_numTf, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(backJButton)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(eTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(takerNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takerInsNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takerStTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takerEtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takerAmTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(car_numTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carInsNumTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carStTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carEtTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carAmTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RejectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(saveInsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(updateInsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateInsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsBtnActionPerformed
        // TODO add your handling code here:
        nTf.setEnabled(false);
        sTf.setEnabled(false);
        eTf.setEnabled(false);
        
        takerNameTf.setEnabled(false);
        car_numTf.setEnabled(false);
        carInsNumTf.setEnabled(true);
        carAmTf.setEnabled(true);
        carEtTf.setEnabled(true);
        carStTf.setEnabled(true);
        takerAmTf.setEnabled(true);
        takerEtTf.setEnabled(true);
        takerInsNumTf.setEnabled(true);
        takerStTf.setEnabled(true);
        


            
//            JOptionPane.showMessageDialog(null, "Active Successful!!");
//            
//        }
     
//        request.setStatus("Processing");
//        
//        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, request);
//        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
            //       }
    }//GEN-LAST:event_updateInsBtnActionPerformed

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        // TODO add your handling code here:
        updateInsBtn.setEnabled(false);
        RejectButton.setEnabled(false);
        for(UserInfo c : request.getSender().getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
            c.setStatus(0);
            System.out.println(request.getSender().getEmployee().getName());
            JOptionPane.showMessageDialog(null, "Please notice user to reupdate information again!");
            
                 }

    }//GEN-LAST:event_RejectButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void saveInsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveInsBtnActionPerformed
        // TODO add your handling code here:
                          
            String name = nTf.getText();
            String ssn = sTf.getText();
            String email = eTf.getText();
            String carNum = car_numTf.getText();
            String takerName = takerNameTf.getText();
            

            
//            String carAm = carAmTf.getText();
//            String takerAm = takerAmTf.getText();
            String carEt = carEtTf.getText();
            String carInsNum = carInsNumTf.getText();
            String takerInsNum = takerInsNumTf.getText();
            String carSt = carStTf.getText();
            String takerEt = takerEtTf.getText();
            String takerSt = takerStTf.getText();
            
            
            double carAm = Double.valueOf(carAmTf.getText());
            double takerAm = Double.valueOf(takerAmTf.getText());
            
            UserInsuranceInfo c =  request.getSender().getEmployee().getUserInsuranceInfoDirectory().addUserInsuranceInfo();

            c.setCarAmount(carAm);
            c.setCarEndTime(carEt);
            c.setTakerName(takerName);
            c.setCarInsId(carInsNum);
            c.setCarNumber(carNum);
            c.setCarStartTime(carSt);
            c.setTakerAmount(takerAm);
            c.setTakerEndTime(takerEt);
            c.setTakerInsId(takerInsNum);           
            c.setTakerStartTime(takerSt);    
            
            for(UserInfo u : request.getSender().getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
                u.setStatus(2);
            }
            JOptionPane.showMessageDialog(null, "Save Successfully!");
            System.out.println(e.getUserInsuranceInfoDirectory().getUserInsuranceInfoDirectory().size());

       // }

        
        
    }//GEN-LAST:event_saveInsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RejectButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField carAmTf;
    private javax.swing.JTextField carEtTf;
    private javax.swing.JTextField carInsNumTf;
    private javax.swing.JTextField carStTf;
    private javax.swing.JTextField car_numTf;
    private javax.swing.JTextField eTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nTf;
    private javax.swing.JTextField sTf;
    private javax.swing.JButton saveInsBtn;
    private javax.swing.JTextField takerAmTf;
    private javax.swing.JTextField takerEtTf;
    private javax.swing.JTextField takerInsNumTf;
    private javax.swing.JTextField takerNameTf;
    private javax.swing.JTextField takerStTf;
    private javax.swing.JButton updateInsBtn;
    // End of variables declaration//GEN-END:variables
}
