/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RdriverRole;



import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Employee.Rdriver.RdriverInfo;
import Business.Employee.User.UserInfo;

import java.awt.CardLayout;
import javax.swing.JPanel;

import Business.Enterprise.Enterprise;
import Business.Organization.ReplacingDriverOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;

import userinterface.RdriverRole.RdriverWorkArea;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.management.relation.Role;


/**
 *
 * @author Hongxi Li
 */


public class RdriverWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
//    private EcoSystem business;
    private EmployeeDirectory employeeList;

  //  private RdriverBisWorkArea RdriverBisWorkArea;
    public RdriverWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
//        showNameTf.setText(Role.roleValueToString(RoleTy).getName());
        this.ecoSystem = ecoSystem;
        this.employeeList = employeeList;
 //       this.RdriverBisWorkArea = RdriverBisWorkArea;
        populate();
//        
    }
    public void populate(){
        for(UserInfo c :account.getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
        System.out.print(c.getStatus());
        /*if(c.getStatus() == 0){
               
                doBisBtn.setEnabled(false);
                AccountBtn.setEnabled(false);
                ProcessingOrderButton.setEnabled(false);
                ApReBtn.setEnabled(false);
                CompletedOrderButton.setEnabled(false);
            }
         if(c.getStatus() == 1){
              
                doBisBtn.setEnabled(false);
                AccountBtn.setEnabled(false);
                ProcessingOrderButton.setEnabled(false);
                ApReBtn.setEnabled(false);
                CompletedOrderButton.setEnabled(true);
        }  
         if(c.getStatus() == 2){
              
                doBisBtn.setEnabled(false);
                AccountBtn.setEnabled(false);
                ProcessingOrderButton.setEnabled(false);
                ApReBtn.setEnabled(false);
                CompletedOrderButton.setEnabled(true);
        }
         if(c.getStatus() == 3){
              
                doBisBtn.setEnabled(false);
                AccountBtn.setEnabled(true);
                ProcessingOrderButton.setEnabled(false);
                ApReBtn.setEnabled(false);
                CompletedOrderButton.setEnabled(true);
        }
         if(c.getStatus() == 4){
              
                doBisBtn.setEnabled(true);
                AccountBtn.setEnabled(true);
                ProcessingOrderButton.setEnabled(true);
                ApReBtn.setEnabled(true);
                CompletedOrderButton.setEnabled(true);
        }*/
         
         
            }
        showNameTf.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountBtn = new javax.swing.JButton();
        doBisBtn = new javax.swing.JButton();
        ApReBtn = new javax.swing.JButton();
        ViewProfileBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showNameTf = new javax.swing.JTextField();
        ProcessingOrderButton = new javax.swing.JButton();
        CompletedOrderButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(65, 192, 110));

        AccountBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AccountBtn.setText("My Account");
        AccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBtnActionPerformed(evt);
            }
        });

        doBisBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        doBisBtn.setText("DO MY BUSINESS!");
        doBisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBisBtnActionPerformed(evt);
            }
        });

        ApReBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ApReBtn.setText("Application Request");
        ApReBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApReBtnActionPerformed(evt);
            }
        });

        ViewProfileBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ViewProfileBtn.setText("View Profile");
        ViewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Rdriver WorkArea");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        showNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNameTfActionPerformed(evt);
            }
        });

        ProcessingOrderButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ProcessingOrderButton.setText("View Order");
        ProcessingOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessingOrderButtonActionPerformed(evt);
            }
        });

        CompletedOrderButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        CompletedOrderButton.setText("Apply Insurance");
        CompletedOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(doBisBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ViewProfileBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProcessingOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ApReBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CompletedOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(showNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(ApReBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(doBisBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProcessingOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(CompletedOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBtnActionPerformed
        // TODO add your handling code here:
        RdriverAccountWorkArea customerFindRdriver = new RdriverAccountWorkArea(userProcessContainer, account, organization, enterprise, ecoSystem);
        userProcessContainer.add("CustomermanagementJPanel", customerFindRdriver);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AccountBtnActionPerformed

    private void doBisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBisBtnActionPerformed
        // TODO add your handling code here:
//        return new CustomerMsgChecker(userProcessContainer, account, (CustomerOrganization)organization, enterprise);
        
        RdriverReceiveCusMsg messageWorkArea = new RdriverReceiveCusMsg(userProcessContainer, account, organization, enterprise, ecoSystem);
        userProcessContainer.add("Usermanagement", messageWorkArea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_doBisBtnActionPerformed

    private void ApReBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApReBtnActionPerformed
        // TODO add your handling code here:

        RdriverMsgChecker RdriverMsgChecker = new RdriverMsgChecker(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("RdrivermanagementJPanel", RdriverMsgChecker);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ApReBtnActionPerformed

    private void ViewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileBtnActionPerformed
        // TODO add your handling code here:
        Employee e = account.getEmployee();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RdriverInfoJPanel", new RdriverInfoJPanel(userProcessContainer, e, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewProfileBtnActionPerformed

    private void showNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showNameTfActionPerformed

    private void ProcessingOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessingOrderButtonActionPerformed
        // TODO add your handling code here:
        RdriverViewOrderList rdriverprocessOder = new RdriverViewOrderList(userProcessContainer, account, organization, ecoSystem);
        userProcessContainer.add("RdrivermanagementJPanel", rdriverprocessOder);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ProcessingOrderButtonActionPerformed

    private void CompletedOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedOrderButtonActionPerformed
        // TODO add your handling code here:
        RdriverMsgAll_Insurance customerMsgInsurance = new RdriverMsgAll_Insurance(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("customerMsgInsurance", customerMsgInsurance);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CompletedOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountBtn;
    private javax.swing.JButton ApReBtn;
    private javax.swing.JButton CompletedOrderButton;
    private javax.swing.JButton ProcessingOrderButton;
    private javax.swing.JButton ViewProfileBtn;
    private javax.swing.JButton doBisBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField showNameTf;
    // End of variables declaration//GEN-END:variables
}
