/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RdriverRole;

import Business.Employee.User.UserInfo;
import Business.Employee.UserAccounterInfo.UserAccounterInfo;
import Business.Enterprise.Enterprise;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.CheckerRole.CheckerProcessCusRq;

/**
 *
 * @author star
 */
public class RdriverViewOrderMsg extends javax.swing.JPanel {

    /**
     * Creates new form RdriverViewOrderMsg
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest request;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    private double c_insurance;
    public RdriverViewOrderMsg(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.c_insurance = c_insurance;
        jComboBox.removeAllItems();
        jComboBox.addItem("No Insurance");
        jComboBox.addItem("2 dollars compensate 50");
        jComboBox.addItem("5 dollars compensate 200");
        jComboBox.addItem("10 dollars compensate 500");
        
        
        messageJTextField3.setText(request.getSender().getEmployee().getName());
        for(UserInfo u : request.getSender().getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
        messageJTextField1.setText(u.getCar_num()); 
        messageJTextField.setText(request.getFrom());
        messageJTextField2.setText(request.getTo());
        messageJTextField4.setText(request.getFrom_time());
        messageJTextField5.setText(request.getNumber());
        CustomerInsTf.setText(request.getC_insurance());
        
        }
        if(request.getStatus().equals("Pending")){
            AssignBtn.setEnabled(false);
        }
        else if(request.getStatus().equals("Sent")){
            AssignBtn.setEnabled(true);
        }
              
                
                
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        messageJTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        messageJTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        messageJTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        messageJTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        messageJTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AssignBtn = new javax.swing.JButton();
        ProcessBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        CustomerInsTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 192, 110));

        jLabel1.setText("Departure:");

        jLabel2.setText("Car_Num:");

        jLabel3.setText("Arrival:");

        jLabel4.setText("Name:");

        jLabel5.setText("Departure Time:");

        jLabel6.setText("Number of people:");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AssignBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AssignBtn.setText("Assign to me");
        AssignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignBtnActionPerformed(evt);
            }
        });

        ProcessBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ProcessBtn.setText("Process!!!");
        ProcessBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Customer Insurance:");

        jLabel8.setText("Select Your Insurance:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setBackground(new java.awt.Color(51, 51, 255));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AccounterRole/7.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(101, 101, 101)
                                        .addComponent(messageJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(79, 79, 79)
                                        .addComponent(messageJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(75, 75, 75)
                                        .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(96, 96, 96)
                                        .addComponent(messageJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(40, 40, 40)
                                        .addComponent(messageJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AssignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(ProcessBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel6)
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CustomerInsTf)
                                        .addComponent(messageJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(messageJTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CustomerInsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcessBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RdriverReceiveCusMsg dwjp = (RdriverReceiveCusMsg) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AssignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignBtnActionPerformed
        // TODO add your handling code here:
        String d_ins = (String)jComboBox.getSelectedItem();
        request.setReceiver(userAccount);
        request.setStatus("Pending");      
        request.setD_insurance(d_ins);
        int index1 = request.getFrom_index();
        int index2 = request.getTo_index();
        int index3 = index1 - index2;
        if(index3 >= 0 ){
            index3 = index1 - index2;
        }
        else if (index3 < 0){
            index3 = index2 - index1;
        }
        double estimated_fee = index3 * 0.8;
        int checkButton = JOptionPane.YES_NO_OPTION;
        int checkResult = JOptionPane.showConfirmDialog(null, "Do you want to accept this order? The estimated fee is "+ estimated_fee, "Check", checkButton);
        if(checkResult == JOptionPane.YES_OPTION){
           
        
        for(UserAccounterInfo useraccounterInfo : request.getSender().getEmployee().getUserAccounterInfoDirectory().getUserAccounterInfoDirectory()){
             
           
        if(request.getC_insurance().startsWith("No")){
             c_insurance = 0.0;
        }
        else if(request.getC_insurance().startsWith("2")){
             c_insurance = 2.0;
        }
        else if(request.getC_insurance().startsWith("5")){
             c_insurance = 5.0;
        }
        else if(request.getC_insurance().startsWith("10")){
             c_insurance = 10.0;
        }
            double balance = useraccounterInfo.getTakerBalance();
            double fee = index3 * useraccounterInfo.getDiscount() + c_insurance;
            double c_fee = index3 * useraccounterInfo.getDiscount();
            double balance2 = (balance - fee);
            
            request.setC_fee(c_fee);
            useraccounterInfo.setTakerBalance(balance2);
            
            LabTestWorkRequest r = new LabTestWorkRequest();
        r.setD_insurance(request.getD_insurance());
        r.setC_insurance(request.getC_insurance());
        r.setSender(request.getSender());
        r.setReceiver(userAccount);
        r.setFrom(request.getFrom());
        r.setTo(request.getTo());
        r.setFrom_time(request.getFrom_time());
        r.setTo_time(request.getTo_time());
        r.setC_fee(c_fee);
        r.setD_fee(c_fee * 0.8);
        r.setNumber(request.getNumber());
        r.setStatus("Pending");
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof CustomerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(r);
            userAccount.getWorkQueue().getWorkRequestList().add(r);
        }
        }
        AssignBtn.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Accept Order Successfully!");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RdriverReceiveCusMsg dwjp = (RdriverReceiveCusMsg) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        if(checkResult == JOptionPane.NO_OPTION){
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RdriverReceiveCusMsg dwjp = (RdriverReceiveCusMsg) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        JOptionPane.showMessageDialog(null, "Please Choose another order.");
        }
        
        
    }//GEN-LAST:event_AssignBtnActionPerformed

    private void ProcessBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessBtnActionPerformed
        // TODO add your handling code here:
        request.setStatus("Processing");
        
        RdriverProcessCusRq processWorkRequestJPanel = new RdriverProcessCusRq(userProcessContainer, userAccount, enterprise, request);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ProcessBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignBtn;
    private javax.swing.JTextField CustomerInsTf;
    private javax.swing.JButton ProcessBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField messageJTextField1;
    private javax.swing.JTextField messageJTextField2;
    private javax.swing.JTextField messageJTextField3;
    private javax.swing.JTextField messageJTextField4;
    private javax.swing.JTextField messageJTextField5;
    // End of variables declaration//GEN-END:variables
}
