/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Employee.EmployeeDirectory;
import Business.Employee.User.UserInfo;
import Business.Employee.UserCarOwner.CarOwnerInfo;
import java.awt.CardLayout;
import javax.swing.JPanel;

import Business.Enterprise.Enterprise;
import Business.Organization.ReplacingDriverOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import userinterface.CustomerRole.CustomerMsgChecker;
import userinterface.CustomerRole.CustomerWorkArea;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;

/**
 *
 * @author Hongxi Li
 */


public class CustomerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkArea
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private EmployeeDirectory employeeList;

    private CustomerMsgChecker CarownerWorkAreaJPanel;
    public CustomerWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
//        valueLabel.setText(enterprise.getName());
        this.ecoSystem = ecoSystem;
        this.employeeList = employeeList;
        this.CarownerWorkAreaJPanel = CarownerWorkAreaJPanel;
        populate();
//        
       }
    
    public void populate(){
        for(UserInfo c :account.getEmployee().getUserInfoDirectory().getUserInfoDirectory()){
        if(c.getStatus() == 0){
               
                FindRDriverBtn.setEnabled(false);
                AccountBtn.setEnabled(false);
                ViewOrderBtn.setEnabled(false);
                ApReBtn.setEnabled(false);
                ApInBtn.setEnabled(false);
            }
         if(c.getStatus() == 1){
              
                FindRDriverBtn.setEnabled(false);
                AccountBtn.setEnabled(false);
                ViewOrderBtn.setEnabled(false);
                ApReBtn.setEnabled(false);
                ApInBtn.setEnabled(true);
        }  
         if(c.getStatus() == 2){
              
                FindRDriverBtn.setEnabled(false);
                AccountBtn.setEnabled(true);
                ViewOrderBtn.setEnabled(false);
                ApReBtn.setEnabled(false);
                ApInBtn.setEnabled(true);
        }
         if(c.getStatus() == 3){
              
                FindRDriverBtn.setEnabled(false);
                AccountBtn.setEnabled(true);
                ViewOrderBtn.setEnabled(false);
                ApReBtn.setEnabled(true);
                ApInBtn.setEnabled(true);
        }
         if(c.getStatus() == 4){
              
                FindRDriverBtn.setEnabled(true);
                AccountBtn.setEnabled(true);
                ViewOrderBtn.setEnabled(true);
                ApReBtn.setEnabled(true);
                ApInBtn.setEnabled(true);
        }
         
        }
        showNameTf.setText(account.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccountBtn = new javax.swing.JButton();
        FindRDriverBtn = new javax.swing.JButton();
        ApReBtn = new javax.swing.JButton();
        ViewProfileBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showNameTf = new javax.swing.JTextField();
        ApInBtn = new javax.swing.JButton();
        ViewOrderBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(205, 207, 211));

        AccountBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AccountBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/30.png"))); // NOI18N
        AccountBtn.setText("My Account");
        AccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBtnActionPerformed(evt);
            }
        });

        FindRDriverBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        FindRDriverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/38.png"))); // NOI18N
        FindRDriverBtn.setText("Replacing Driver");
        FindRDriverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindRDriverBtnActionPerformed(evt);
            }
        });

        ApReBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ApReBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/33.png"))); // NOI18N
        ApReBtn.setText("Verification");
        ApReBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApReBtnActionPerformed(evt);
            }
        });

        ViewProfileBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ViewProfileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AdministrativeRole/5.png"))); // NOI18N
        ViewProfileBtn.setText("Profile");
        ViewProfileBtn.setActionCommand("Profile");
        ViewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProfileBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 36)); // NOI18N
        jLabel2.setText("Customer WorkArea");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        showNameTf.setEditable(false);
        showNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNameTfActionPerformed(evt);
            }
        });

        ApInBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ApInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/34.png"))); // NOI18N
        ApInBtn.setText("Apply Insurance");
        ApInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApInBtnActionPerformed(evt);
            }
        });

        ViewOrderBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ViewOrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/CustomerRole/35.png"))); // NOI18N
        ViewOrderBtn.setText("View Order");
        ViewOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrderBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("NOTES:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("1. All the user need to apply the insurance and upload your information");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("2. Once you have accecpeted by the checker, you can use the system.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FindRDriverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ViewProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ApInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ApReBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(AccountBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ViewOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(showNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewOrderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ApInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApReBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindRDriverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBtnActionPerformed
        // TODO add your handling code here:
        CustomerAccountWorkArea customerFindRdriver = new CustomerAccountWorkArea(userProcessContainer, account, organization, enterprise, ecoSystem);
        userProcessContainer.add("CustomermanagementJPanel", customerFindRdriver);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AccountBtnActionPerformed

    private void FindRDriverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindRDriverBtnActionPerformed
        // TODO add your handling code here:
//      
        CustomerMsgRdriver customerFindRdriver = new CustomerMsgRdriver(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("CustomermanagementJPanel", customerFindRdriver);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_FindRDriverBtnActionPerformed

    private void ApReBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApReBtnActionPerformed
        // TODO add your handling code here:

        CustomerMsgChecker customerMsgChecker = new CustomerMsgChecker(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("CustomermanagementJPanel", customerMsgChecker);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_ApReBtnActionPerformed

    private void ViewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProfileBtnActionPerformed
        // TODO add your handling code here:
        Employee e = account.getEmployee();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("CarownerInfoJPanel", new CustomerInfoJPanel(userProcessContainer, e, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewProfileBtnActionPerformed

    private void showNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showNameTfActionPerformed

    private void ApInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApInBtnActionPerformed
        // TODO add your handling code here:
        CustomerMsgAll_Insurance customerMsgInsurance = new CustomerMsgAll_Insurance(userProcessContainer, account, organization, enterprise);
        userProcessContainer.add("customerMsgInsurance", customerMsgInsurance);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ApInBtnActionPerformed

    private void ViewOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrderBtnActionPerformed
        // TODO add your handling code here:
        CustomerViewOrderList CustomerMsgAccounter = new CustomerViewOrderList(userProcessContainer, account, organization, ecoSystem);
        userProcessContainer.add("CustomerMsgAccounter", CustomerMsgAccounter);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewOrderBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountBtn;
    private javax.swing.JButton ApInBtn;
    private javax.swing.JButton ApReBtn;
    private javax.swing.JButton FindRDriverBtn;
    private javax.swing.JButton ViewOrderBtn;
    private javax.swing.JButton ViewProfileBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField showNameTf;
    // End of variables declaration//GEN-END:variables
}
