/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import userinterface.CustomerRole.CustomerMsgChecker;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CheckerOrganization;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.Organization.ReplacingDriverOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class CustomerRqToRdriver extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public CustomerRqToRdriver(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        
        InsuranceComboBox.removeAllItems();
        FromComboBox.removeAllItems();
        ToComboBox.removeAllItems();
        
        InsuranceComboBox.addItem("No Insurance");
        InsuranceComboBox.addItem("2 dollars compensate 50");
        InsuranceComboBox.addItem("5 dollars compensate 200");
        InsuranceComboBox.addItem("10 dollars compensate 500");
        
        for(int i=1;i<11;i++){
        FromComboBox.addItem("A"+i);
        FromComboBox.addItem("B"+i);
        FromComboBox.addItem("C"+i);
        FromComboBox.addItem("D"+i);
        FromComboBox.addItem("E"+i);
        FromComboBox.addItem("F"+i);
        FromComboBox.addItem("G"+i);
        FromComboBox.addItem("H"+i);
        FromComboBox.addItem("I"+i);
        FromComboBox.addItem("J"+i);
        
        ToComboBox.addItem("A"+i);
        ToComboBox.addItem("B"+i);
        ToComboBox.addItem("C"+i);
        ToComboBox.addItem("D"+i);
        ToComboBox.addItem("E"+i);
        ToComboBox.addItem("F"+i);
        ToComboBox.addItem("G"+i);
        ToComboBox.addItem("H"+i);
        ToComboBox.addItem("I"+i);
        ToComboBox.addItem("J"+i);
          
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        messageJTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        messageJTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InsuranceComboBox = new javax.swing.JComboBox();
        FromComboBox = new javax.swing.JComboBox();
        ToComboBox = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 130, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Departure:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        backJButton.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 100, 50));

        valueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Arrival:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Departure Time:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));
        add(messageJTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 89, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Number of people:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));
        add(messageJTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 89, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Insurance:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        InsuranceComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(InsuranceComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        FromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(FromComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        ToComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ToComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel15.setBackground(new java.awt.Color(51, 51, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/AccounterRole/7.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        String departure = (String)FromComboBox.getSelectedItem();
        String arrival = (String)ToComboBox.getSelectedItem();
        String departure_time = messageJTextField4.getText();
        int FromIndex = FromComboBox.getSelectedIndex();
        int ToIndex = ToComboBox.getSelectedIndex();
        String num = messageJTextField5.getText();
        String ins = (String)InsuranceComboBox.getSelectedItem();
       
        
        int index3 = FromIndex - ToIndex;
        if(index3 >= 0 ){
            index3 = FromIndex - ToIndex;
        }
        else if (index3 < 0){
            index3 = ToIndex - FromIndex;
        }
        double estimated_fee = index3;
        int checkButton = JOptionPane.YES_NO_OPTION;
        int checkResult = JOptionPane.showConfirmDialog(null, "Do you want to call Replacing Driver? The estimated fee is "+ estimated_fee, "Check", checkButton);
        if(checkResult == JOptionPane.YES_OPTION){
        JOptionPane.showMessageDialog(null, "Send Order successfully!");
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setFrom(departure);
        request.setFrom_index(FromIndex);
        request.setFrom_time(departure_time);
        request.setTo(arrival);
        request.setTo_index(ToIndex);
        request.setNumber(num);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setC_insurance(ins);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof ReplacingDriverOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
         }
        }
        else if(checkResult == JOptionPane.NO_OPTION){
        JOptionPane.showMessageDialog(null, "Edit Information Again !");
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        }
        JOptionPane.showMessageDialog(null, "You have submitted Request successfully!");
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FromComboBox;
    private javax.swing.JComboBox InsuranceComboBox;
    private javax.swing.JComboBox ToComboBox;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField messageJTextField4;
    private javax.swing.JTextField messageJTextField5;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
