/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Hongxi Li
 */

import Business.Person; 
import javax.swing.JOptionPane;




public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
    private Person person;
    
    public CreatePanel(Person person) {
        initComponents();
        
        this.person = person;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LACityTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SACountryTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        DOBTextField = new javax.swing.JTextField();
        SACityTextField = new javax.swing.JTextField();
        firName = new javax.swing.JLabel();
        WACityTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        LACountryTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lasNameTextField = new javax.swing.JTextField();
        LAStrLine2TextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SAZipcodeTextField = new javax.swing.JTextField();
        WAStrLine2TextField = new javax.swing.JTextField();
        LAZipcodeTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        SAStateTextField = new javax.swing.JTextField();
        SAStrLine1TextField = new javax.swing.JTextField();
        LAStrLine1TextField = new javax.swing.JTextField();
        firNameTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        WAStateTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        LAStateTextField = new javax.swing.JTextField();
        WAStrLine1TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        WACountryTextField = new javax.swing.JTextField();
        WAZipcodeTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        SAStrLine2TextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        subBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        LACityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LACityTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Street Address:");

        jLabel6.setText("Local Address");

        jLabel22.setText("City");

        jLabel14.setText("Street Line1");

        jLabel20.setText("Street Line1");

        jLabel19.setText("Country");

        SACountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SACountryTextFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Zip Code");

        DOBTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBTextFieldActionPerformed(evt);
            }
        });

        SACityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SACityTextFieldActionPerformed(evt);
            }
        });

        firName.setText("First Name:");

        WACityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WACityTextFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("City");

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        LACountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LACountryTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Zip Code");

        jLabel16.setText("City");

        jLabel4.setText("DOB(YYYY/MM/DD)");

        jLabel2.setText("Last  Name:");

        jLabel7.setText("Sweet Address");

        lasNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lasNameTextFieldActionPerformed(evt);
            }
        });

        LAStrLine2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAStrLine2TextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Street Line2");

        SAZipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAZipcodeTextFieldActionPerformed(evt);
            }
        });

        WAStrLine2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAStrLine2TextFieldActionPerformed(evt);
            }
        });

        LAZipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAZipcodeTextFieldActionPerformed(evt);
            }
        });

        jLabel18.setText("Zip Code");

        jLabel25.setText("Country");

        jLabel13.setText("Country");

        SAStateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAStateTextFieldActionPerformed(evt);
            }
        });

        SAStrLine1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAStrLine1TextFieldActionPerformed(evt);
            }
        });

        LAStrLine1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAStrLine1TextFieldActionPerformed(evt);
            }
        });

        firNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firNameTextFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("Street Line2");

        WAStateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAStateTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("State");

        LAStateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAStateTextFieldActionPerformed(evt);
            }
        });

        WAStrLine1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAStrLine1TextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Street Line1");

        WACountryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WACountryTextFieldActionPerformed(evt);
            }
        });

        WAZipcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WAZipcodeTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("State");

        SAStrLine2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAStrLine2TextFieldActionPerformed(evt);
            }
        });

        jLabel23.setText("State");

        jLabel9.setText("Street Line2");

        jLabel5.setText("Work Address");

        subBtn.setText("Submit");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Person Profile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(subBtn)))
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lasNameTextField)
                                        .addComponent(firNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(addressTextField))
                            .addGap(61, 61, 61))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(WAStrLine1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(WACountryTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(WAZipcodeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(WAStateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(WACityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(WAStrLine2TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LAStrLine1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LACountryTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LAZipcodeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LAStateTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LACityTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LAStrLine2TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(SAStrLine1TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SACountryTextField)
                                            .addComponent(SAZipcodeTextField)
                                            .addComponent(SAStateTextField)
                                            .addComponent(SACityTextField)
                                            .addComponent(SAStrLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel7))))
                    .addGap(30, 30, 30)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                .addComponent(subBtn)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firName)
                        .addComponent(firNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lasNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DOBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel5))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(WAStrLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(WAStrLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(WACityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(WAStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(WAZipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(WACountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(LAStrLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(LAStrLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(LACityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(LAStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(LAZipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(LACountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(SAStrLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(SAStrLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(SACityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(SAStateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(SAZipcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(SACountryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(55, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firNameTextFieldActionPerformed

    private void lasNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lasNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lasNameTextFieldActionPerformed

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void DOBTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBTextFieldActionPerformed

    private void WAStrLine1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAStrLine1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAStrLine1TextFieldActionPerformed

    private void WAStrLine2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAStrLine2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAStrLine2TextFieldActionPerformed

    private void WACityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WACityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WACityTextFieldActionPerformed

    private void WAStateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAStateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAStateTextFieldActionPerformed

    private void WAZipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WAZipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WAZipcodeTextFieldActionPerformed

    private void WACountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WACountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WACountryTextFieldActionPerformed

    private void LAStrLine1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAStrLine1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAStrLine1TextFieldActionPerformed

    private void LAStrLine2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAStrLine2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAStrLine2TextFieldActionPerformed

    private void LACityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LACityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LACityTextFieldActionPerformed

    private void LAStateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAStateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAStateTextFieldActionPerformed

    private void LAZipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAZipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LAZipcodeTextFieldActionPerformed

    private void LACountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LACountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LACountryTextFieldActionPerformed

    private void SAStrLine1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAStrLine1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAStrLine1TextFieldActionPerformed

    private void SAStrLine2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAStrLine2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAStrLine2TextFieldActionPerformed

    private void SACityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SACityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SACityTextFieldActionPerformed

    private void SAStateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAStateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAStateTextFieldActionPerformed

    private void SAZipcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAZipcodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SAZipcodeTextFieldActionPerformed

    private void SACountryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SACountryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SACountryTextFieldActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        person.setFirName(firNameTextField.getText());
        person.setLasName(lasNameTextField.getText());
        person.setAddress(addressTextField.getText());
        person.setDate(DOBTextField.getText());
        
        person.setWAStrLine1(WAStrLine1TextField.getText());
        person.setWAStrLine2(WAStrLine2TextField.getText());
        person.setWACity(WACityTextField.getText());
        person.setWAState(WAStateTextField.getText());
        person.setWAZipcode(WAZipcodeTextField.getText());
        person.setWACountry(WACountryTextField.getText());
        
        person.setLAStrLine1(LAStrLine1TextField.getText());
        person.setLAStrLine2(LAStrLine2TextField.getText());
        person.setLACity(LACityTextField.getText());
        person.setLAState(LAStateTextField.getText());
        person.setLAZipcode(LAZipcodeTextField.getText());
        person.setLACountry(LACountryTextField.getText());
        
        person.setSAStrLine1(SAStrLine1TextField.getText());
        person.setSAStrLine2(SAStrLine2TextField.getText());
        person.setSACity(SACityTextField.getText());
        person.setSAState(SAStateTextField.getText());
        person.setSAZipcode(SAZipcodeTextField.getText());
        person.setSACountry(SACountryTextField.getText());
        
        
        //
        JOptionPane.showMessageDialog(null, "create Person successfully");
        
    }//GEN-LAST:event_subBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOBTextField;
    private javax.swing.JTextField LACityTextField;
    private javax.swing.JTextField LACountryTextField;
    private javax.swing.JTextField LAStateTextField;
    private javax.swing.JTextField LAStrLine1TextField;
    private javax.swing.JTextField LAStrLine2TextField;
    private javax.swing.JTextField LAZipcodeTextField;
    private javax.swing.JTextField SACityTextField;
    private javax.swing.JTextField SACountryTextField;
    private javax.swing.JTextField SAStateTextField;
    private javax.swing.JTextField SAStrLine1TextField;
    private javax.swing.JTextField SAStrLine2TextField;
    private javax.swing.JTextField SAZipcodeTextField;
    private javax.swing.JTextField WACityTextField;
    private javax.swing.JTextField WACountryTextField;
    private javax.swing.JTextField WAStateTextField;
    private javax.swing.JTextField WAStrLine1TextField;
    private javax.swing.JTextField WAStrLine2TextField;
    private javax.swing.JTextField WAZipcodeTextField;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel firName;
    private javax.swing.JTextField firNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lasNameTextField;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
